C_FLOOR = P_FLOOR = '.'
D_STAIRS = U_STAIRS = '>'
BARS = 'b'
WALL = 'W'
STONE = 'S'
STARTPOINT = 'P'

FLOOR = {P_FLOOR, C_FLOOR, STARTPOINT}
STAIRS = {D_STAIRS, U_STAIRS}
TRAVERSABLE = STAIRS | FLOOR
